package kereso;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author BenZe
 */
public class Cegkereso extends javax.swing.JFrame {

    String filePath = "E:/places.bqf";
    
    public Cegkereso() {
        initComponents();
        otherMatches.setListData(new String[0]);
        this.setLocationRelativeTo(null);
        this.setTitle("Bitep cégkereső");
    }
    
    private void searchExactly() {
        try{
            Kereso search = new Kereso(filePath);
            if(search.searchTheOne(keresTf.getText())){
                foundCompany.setText(search.getCompany());
                foundBuilding.setText(search.getBuilding());
                foundZone.setText(search.getZone());  
                foundInfo.setText(search.getInformation());
                
            }
            else {
                String[] elements = search.searchOthers(keresTf.getText()).toArray(new String[0]);  
                otherMatches.setListData(elements);
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Hiba: " + ex);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keresTf = new javax.swing.JTextField();
        keresBtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        otherMatches = new javax.swing.JList<>();
        label1 = new javax.swing.JLabel();
        foundCompany = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        foundBuilding = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        foundZone = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        foundInfo = new javax.swing.JLabel();
        compRb = new javax.swing.JRadioButton();
        InfoRb = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        keresTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keresTfKeyPressed(evt);
            }
        });

        keresBtn.setText("KERES");
        keresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresBtnActionPerformed(evt);
            }
        });

        otherMatches.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        otherMatches.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                otherMatchesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(otherMatches);

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("Cég:");

        foundCompany.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foundCompany.setText("-");

        label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label2.setText("Épület:");

        foundBuilding.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        foundBuilding.setText("-");

        label3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label3.setText("Zóna:");

        foundZone.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        foundZone.setText("-");

        label4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label4.setText("Egyéb:");

        foundInfo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        foundInfo.setText("-");
        foundInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        foundInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        compRb.setText("Cég név");

        InfoRb.setText("Információ keresés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2)
                                .addGap(18, 18, 18)
                                .addComponent(foundBuilding))
                            .addComponent(keresTf, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keresBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4)
                        .addGap(18, 18, 18)
                        .addComponent(foundInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3)
                        .addGap(18, 18, 18)
                        .addComponent(foundZone)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(compRb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addGap(18, 18, 18)
                                .addComponent(foundCompany)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InfoRb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(keresTf)
                            .addComponent(keresBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compRb)
                            .addComponent(InfoRb))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1)
                            .addComponent(foundCompany))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2)
                            .addComponent(foundBuilding))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3)
                            .addComponent(foundZone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foundInfo)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresBtnActionPerformed

        searchExactly();
    }//GEN-LAST:event_keresBtnActionPerformed

    private void otherMatchesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_otherMatchesValueChanged
        try{
            Kereso search = new Kereso(filePath);
            search.quickSearch(otherMatches.getSelectedValue());
            foundCompany.setText(search.getCompany());
            foundBuilding.setText(search.getBuilding());
            foundZone.setText(search.getZone()); 
            String vmi = "<html>" + search.getInformation().replaceAll(",", "<br>");
            foundInfo.setText(vmi + "<html");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Hiba: " + ex);
        }
    }//GEN-LAST:event_otherMatchesValueChanged

    private void keresTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keresTfKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            searchExactly();
        }
    }//GEN-LAST:event_keresTfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cegkereso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cegkereso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cegkereso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cegkereso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cegkereso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton InfoRb;
    private javax.swing.JRadioButton compRb;
    private javax.swing.JLabel foundBuilding;
    private javax.swing.JLabel foundCompany;
    private javax.swing.JLabel foundInfo;
    private javax.swing.JLabel foundZone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton keresBtn;
    private javax.swing.JTextField keresTf;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JList<String> otherMatches;
    // End of variables declaration//GEN-END:variables
}
